# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246ced20b34e216dd8a6978a6fa83a03283f2302fcd77a577c3ea5546d37cbc5316500f2ad81c66539428e380fc2d6666fabf439756639a38ae3bed739591fe9

test:
  secret_key_base: a65b1f6509ea0b84e0fb6b33297127ac9782e7a44c6d3db02a21efd40adc3079c5394d3834483765e2705025306af5cf3970bfd5340d92c52fdcb0f9dfeb208c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
